/******************************************************************************
; Resideo Residential Thermal Solutions                                       *
; Turanka 96/1236                                                             *
; 627 00 Brno, Czech Republic                                                 *
;                                                                             *
; Creation date: 2021-09-15           Author: Herbrych, Vojtech               *
;******************************************************************************
;
; File: Polarity.H
;
;******************************************************************************
; SVN header
;  $Id: Polarity.H 114802 2021-09-15 14:03:07Z Stepanek, Michal $
******************************************************************************/

void Polarity_Init(void);
void Polarity_MainLoop(void);
