/******************************************************************************
; Resideo Residential Thermal Solutions                                       *
; Turanka 96/1236                                                             *
; 627 00 Brno, Czech Republic                                                 *
;                                                                             *
; Creation date: 2021-08-10           Author: Herbrych, Vojtech               *
;******************************************************************************
;
; File: OutputType.H
;
;******************************************************************************
; SVN header
;  $Id: OutputType.H 114363 2021-08-11 17:52:37Z Stepanek, Michal $
******************************************************************************/


/******************************************************************************
; GLOBAL FUNCTIONS
;*****************************************************************************/
void OutputType_MainLoop(void);

uint16_t uwOutputType_Get_0(void);
uint16_t uwOutputType_Get_1(void);
uint16_t uwOutputType_Get_2(void);
uint16_t uwOutputType_Get_3(void);
uint16_t uwOutputType_Get_4(void);
uint16_t uwOutputType_Get_5(void);
uint16_t uwOutputType_Get_6(void);
uint16_t uwOutputType_Get_7(void);
uint16_t uwOutputType_Get_8(void);
uint16_t uwOutputType_Get_9(void);
uint16_t uwOutputType_Get_A(void);
uint16_t uwOutputType_Get_B(void);
uint16_t uwOutputType_Get_C(void);
uint16_t uwOutputType_Get_D(void);
uint16_t uwOutputType_Get_E(void);
uint16_t uwOutputType_Get_F(void);


bool bOutputType_Set_0(uint16_t x);
bool bOutputType_Set_1(uint16_t x);
bool bOutputType_Set_2(uint16_t x);
bool bOutputType_Set_3(uint16_t x);
bool bOutputType_Set_4(uint16_t x);
bool bOutputType_Set_5(uint16_t x);
bool bOutputType_Set_6(uint16_t x);
bool bOutputType_Set_7(uint16_t x);
bool bOutputType_Set_8(uint16_t x);
bool bOutputType_Set_9(uint16_t x);
bool bOutputType_Set_A(uint16_t x);
bool bOutputType_Set_B(uint16_t x);
bool bOutputType_Set_C(uint16_t x);
bool bOutputType_Set_D(uint16_t x);
bool bOutputType_Set_E(uint16_t x);
bool bOutputType_Set_F(uint16_t x);

