/******************************************************************************
; Resideo Residential Thermal Solutions                                       *
; Turanka 96/1236                                                             *
; 627 00 Brno, Czech Republic                                                 *
;                                                                             *
; Creation date: 2021-08-10           Author: Herbrych, Vojtech               *
;******************************************************************************
;
; File: PwmInput.H
;
;******************************************************************************
; SVN header
;  $Id: PwmInput.H 116666 2022-02-02 12:41:13Z Stepanek, Michal $
******************************************************************************/


/******************************************************************************
; GLOBAL FUNCTIONS
;*****************************************************************************/
float32_t fPwmInput_DutyCycle_Get_0(void);
float32_t fPwmInput_DutyCycle_Get_1(void);
float32_t fPwmInput_DutyCycle_Get_2(void);
float32_t fPwmInput_DutyCycle_Get_3(void);
float32_t fPwmInput_DutyCycle_Get_4(void);
float32_t fPwmInput_DutyCycle_Get_5(void);
float32_t fPwmInput_DutyCycle_Get_6(void);
float32_t fPwmInput_DutyCycle_Get_7(void);
float32_t fPwmInput_DutyCycle_Get_8(void);
float32_t fPwmInput_DutyCycle_Get_9(void);
float32_t fPwmInput_DutyCycle_Get_A(void);
float32_t fPwmInput_DutyCycle_Get_B(void);
float32_t fPwmInput_DutyCycle_Get_C(void);
float32_t fPwmInput_DutyCycle_Get_D(void);
float32_t fPwmInput_DutyCycle_Get_E(void);
float32_t fPwmInput_DutyCycle_Get_F(void);
float32_t fPwmInput_Frequency_Get_0(void);
float32_t fPwmInput_Frequency_Get_1(void);
float32_t fPwmInput_Frequency_Get_2(void);
float32_t fPwmInput_Frequency_Get_3(void);
float32_t fPwmInput_Frequency_Get_4(void);
float32_t fPwmInput_Frequency_Get_5(void);
float32_t fPwmInput_Frequency_Get_6(void);
float32_t fPwmInput_Frequency_Get_7(void);
float32_t fPwmInput_Frequency_Get_8(void);
float32_t fPwmInput_Frequency_Get_9(void);
float32_t fPwmInput_Frequency_Get_A(void);
float32_t fPwmInput_Frequency_Get_B(void);
float32_t fPwmInput_Frequency_Get_C(void);
float32_t fPwmInput_Frequency_Get_D(void);
float32_t fPwmInput_Frequency_Get_E(void);
float32_t fPwmInput_Frequency_Get_F(void);

uint16_t uwPwmInput_DutyCycle_Get_0(void);
uint16_t uwPwmInput_DutyCycle_Get_1(void);
uint16_t uwPwmInput_DutyCycle_Get_2(void);
uint16_t uwPwmInput_DutyCycle_Get_3(void);
uint16_t uwPwmInput_DutyCycle_Get_4(void);
uint16_t uwPwmInput_DutyCycle_Get_5(void);
uint16_t uwPwmInput_DutyCycle_Get_6(void);
uint16_t uwPwmInput_DutyCycle_Get_7(void);
uint16_t uwPwmInput_DutyCycle_Get_8(void);
uint16_t uwPwmInput_DutyCycle_Get_9(void);
uint16_t uwPwmInput_DutyCycle_Get_A(void);
uint16_t uwPwmInput_DutyCycle_Get_B(void);
uint16_t uwPwmInput_DutyCycle_Get_C(void);
uint16_t uwPwmInput_DutyCycle_Get_D(void);
uint16_t uwPwmInput_DutyCycle_Get_E(void);
uint16_t uwPwmInput_DutyCycle_Get_F(void);
uint16_t uwPwmInput_Frequency_Get_0(void);
uint16_t uwPwmInput_Frequency_Get_1(void);
uint16_t uwPwmInput_Frequency_Get_2(void);
uint16_t uwPwmInput_Frequency_Get_3(void);
uint16_t uwPwmInput_Frequency_Get_4(void);
uint16_t uwPwmInput_Frequency_Get_5(void);
uint16_t uwPwmInput_Frequency_Get_6(void);
uint16_t uwPwmInput_Frequency_Get_7(void);
uint16_t uwPwmInput_Frequency_Get_8(void);
uint16_t uwPwmInput_Frequency_Get_9(void);
uint16_t uwPwmInput_Frequency_Get_A(void);
uint16_t uwPwmInput_Frequency_Get_B(void);
uint16_t uwPwmInput_Frequency_Get_C(void);
uint16_t uwPwmInput_Frequency_Get_D(void);
uint16_t uwPwmInput_Frequency_Get_E(void);
uint16_t uwPwmInput_Frequency_Get_F(void);

